version: 2

references:
  workspace_root: &workspace_root
    /tmp/workspace

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  load_code: &load_code
    run:
      name: load code from workspace
      command: |
        mv /tmp/workspace/bigcode-tools/* /tmp/workspace/bigcode-tools/.[!.]* .


jobs:
  fetch_project:
    docker:
      - image: circleci/node:6

    working_directory: ~/bigcode-tools

    steps:
      - checkout
      - run: git log --format=%B -n1 | ./misc/git-hooks/commit-msg
      - run:
          command: |
            mkdir -p /tmp/workspace/bigcode-tools
            mv * .[!.]* /tmp/workspace/bigcode-tools/
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - bigcode-tools

  test_nodejs_ast:
    docker:
      - image: circleci/node:6
    working_directory: ~/bigcode-tools
    steps:
      - *attach_workspace
      - *load_code
      - run: cd bigcode-astgen/javascript && yarn
      - run: cd bigcode-astgen/javascript && yarn test

  test_java_ast:
    docker:
      - image: java:8-jdk
    working_directory: ~/bigcode-tools
    steps:
      - *attach_workspace
      - *load_code
      - run: cd bigcode-astgen/java && ./gradlew assemble
      - run: cd bigcode-astgen/java && ./gradlew test

  test_ast_tools:
    docker:
      - image: tuvistavie/sbt:1.0
    working_directory: ~/bigcode-tools
    steps:
      - *attach_workspace
      - *load_code
      - run: cd bigcode-ast-tools && sbt test:compile
      - run: cd bigcode-ast-tools && sbt test:test

  test_code_fetcher:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/bigcode-tools
    steps:
      - *attach_workspace
      - *load_code
      - run: cd bigcode-fetcher && pip install --user -r requirements.txt
      - run: cd bigcode-fetcher && python -m nose

  test_python_ast:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/bigcode-tools
    steps:
      - *attach_workspace
      - *load_code
      - run: sudo apt install python-dev
      - run: cd bigcode-astgen/python && pip install --user -r requirements.txt
      - run: cd bigcode-astgen/python && python -m tox

  test_tokenizer:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/bigcode-tools
    steps:
      - *attach_workspace
      - *load_code
      - run: cd bigcode-tokenizer && pip install --user -r requirements.txt
      - run: cd bigcode-tokenizer && python -m nose

  build_docker_image:
    docker:
      - image: docker:stable
    working_directory: ~/bigcode-tools
    steps:
      - *attach_workspace
      - *load_code
      - setup_remote_docker
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t tuvistavie/bigcode-tools:$TAG .
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          docker push tuvistavie/bigcode-tools:$TAG
          docker tag tuvistavie/bigcode-tools:$TAG tuvistavie/bigcode-tools:latest
          docker push tuvistavie/bigcode-tools:latest


workflows:
  version: 2
  test_all:
    jobs:
      - fetch_project
      - test_ast_tools:
          requires:
            - fetch_project
      - test_nodejs_ast:
          requires:
            - fetch_project
      - test_python_ast:
          requires:
            - fetch_project
      - test_java_ast:
          requires:
            - fetch_project
      - test_code_fetcher:
          requires:
            - fetch_project
      - test_tokenizer:
          requires:
            - fetch_project
      - build_docker_image:
          filters:
            branches:
              only:
                - master
          requires:
            - test_nodejs_ast
            - test_python_ast
            - test_java_ast
            - test_code_fetcher
            - test_ast_tools
            - test_tokenizer
